const data = {
  tickets: [
    {
      name: 'Recursion',
      slug: 'recursion',
      category: 'tickets',
      image: '',
      price: 25,
      brand: null,
      rating: null,
      numReviews: null,
      countInStock: null,
      description: `D'n'B @The Player's Lounge`,
    },
  ],
  products: [
    {
      name: 'Pro.ground Tee',
      slug: 'protocol-tee',
      category: 'Tee',
      image: '/assets/images/5026_CLASSIC_TEE_MAIN__06489.jpeg',
      price: 30,
      brand: 'Protocol Underground',
      rating: null,
      numReviews: null,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Pure Tee',
      slug: 'pure-tee',
      category: 'Tee',
      image: '/assets/images/5027_CLASSIC_POCKET_TEE_MAIN__52659.jpeg',
      price: 30,
      brand: 'Protocol Underground',
      rating: null,
      numReviews: null,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: `Most Important Tee`,
      slug: 'most-important-tee',
      category: 'Tee',
      image: '/assets/images/5026G_CLASSIC_ORGANIC_TEE_MAIN__78407.jpeg',
      price: 30,
      brand: 'Protocol Underground',
      rating: null,
      numReviews: null,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: `Pro.ground Dad Hat`,
      slug: 'pro-ground-dad-hat',
      category: 'Cap',
      image: '/assets/images/1142_ICON_NYLON_CAP_BLACK__21196.jpeg',
      price: 30,
      brand: 'Protocol Underground',
      rating: null,
      numReviews: null,
      countInStock: 20,
      description: 'A popular cap',
    },
  ],
  nfts: [
    {
      name: 'Protocol01',
      slug: 'protocol01',
      category: 'nft',
      image: '',
      price: 100,
      brand: null,
      rating: null,
      numReviews: null,
      countInStock: null,
      description: `Dreamy Lofi mixed by our very own`,
    },
  ],
};

export default data;
